# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  VERSION: ""
  BUILD_DIR: build
  DIST_DIR: build/dist

  APP_NAME: "myapp"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  start:
    cmds:
      - ./build/tingly start

  build:
    cmds:
      - task: ui:dist
      - |
        mkdir -p build
        go build -o ./build/tingly ./cmd/tingly

  dev:
    cmds:
      - task: ui:dist
      - |
        go run ./cmd/tingly start

  ui:dev:
    cmds:
      - |
        cd frontend; pnpm dev

  ui:dist:
    cmds:
      - |
        cd frontend; pnpm build
      - |
        cp -R frontend/dist internal/server/web/dist

  dist:
    desc: Build cross-platform distributions for Windows, Linux, and macOS
    cmds:
      - task: ui:dist
      - |
        echo "Building distributions for version {{.VERSION}}..."
        
        # Create distribution directory
        mkdir -p {{.DIST_DIR}}
        
        # Build for Windows (amd64)
        echo "Building for Windows (amd64)..."
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.DIST_DIR}}/tingly-{{.VERSION}}-windows-amd64.exe ./cmd/tingly
        
        # Build for Linux (amd64)
        echo "Building for Linux (amd64)..."
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.DIST_DIR}}/tingly-{{.VERSION}}-linux-amd64 ./cmd/tingly
        
        # Build for macOS (amd64)
        echo "Building for macOS (amd64)..."
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.DIST_DIR}}/tingly-{{.VERSION}}-darwin-amd64 ./cmd/tingly
        
        # Build for macOS (arm64)
        echo "Building for macOS (arm64)..."
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.DIST_DIR}}/tingly-{{.VERSION}}-darwin-arm64 ./cmd/tingly
        
        # Create archives
        echo "Creating archives..."
        cd {{.DIST_DIR}}
        ls
        
        # # Windows archive (zip)
        # zip -q tingly-{{.VERSION}}-windows-amd64.zip tingly-{{.VERSION}}-windows-amd64.exe
        
        # # Linux archive (tar.gz)
        # tar -czf tingly-{{.VERSION}}-linux-amd64.tar.gz tingly-{{.VERSION}}-linux-amd64
        
        # # macOS archives (tar.gz)
        # tar -czf tingly-{{.VERSION}}-darwin-amd64.tar.gz tingly-{{.VERSION}}-darwin-amd64
        # tar -czf tingly-{{.VERSION}}-darwin-arm64.tar.gz tingly-{{.VERSION}}-darwin-arm64
        
        # # Create universal macOS binary
        # echo "Creating universal macOS binary..."
        # lipo -create -output tingly-{{.VERSION}}-darwin-universal tingly-{{.VERSION}}-darwin-amd64 tingly-{{.VERSION}}-darwin-arm64
        # tar -czf tingly-{{.VERSION}}-darwin-universal.tar.gz tingly-{{.VERSION}}-darwin-universal
        
        # # Clean up binaries after creating archives
        # rm -f tingly-{{.VERSION}}-windows-amd64.exe tingly-{{.VERSION}}-linux-amd64 tingly-{{.VERSION}}-darwin-amd64 tingly-{{.VERSION}}-darwin-arm64 tingly-{{.VERSION}}-darwin-universal
        
        # cd ../..
        
        # # List created files
        # echo "Build completed! Created files:"
        # ls -la {{.DIST_DIR}}/
        
        # echo ""
        # echo "Distribution files created in {{.DIST_DIR}}/:"
        # echo "- tingly-{{.VERSION}}-windows-amd64.zip"
        # echo "- tingly-{{.VERSION}}-linux-amd64.tar.gz"
        # echo "- tingly-{{.VERSION}}-darwin-amd64.tar.gz"
        # echo "- tingly-{{.VERSION}}-darwin-arm64.tar.gz"
        # echo "- tingly-{{.VERSION}}-darwin-universal.tar.gz"

  release:
    desc: Create and push git tag with version passed as parameter. run as 'VERSION=v0.0.9 task release'
    cmds:
      - |
        # Get version from parameter
        VERSION="${VERSION:-}"

        # Check if version is provided
        if [ -z "$VERSION" ]; then
          echo "Error: VERSION parameter is required!"
          echo "Usage: VERSION=v0.0.9 task release"
          exit 1
        fi

        # Validate version format
        if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Invalid version format: $VERSION"
          echo "Expected format: v1.2.3"
          exit 1
        fi

        # Check if tag already exists
        if git tag | grep -q "^${VERSION}$"; then
          echo "Error: Tag $VERSION already exists!"
          echo "Choose a new version and try again"
          exit 1
        fi

        # Create and push tag
        echo "Creating tag $VERSION..."
        git tag "$VERSION"

        echo "Pushing tag to origin..."
        git push origin "$VERSION"

        echo "✅ Distribution started! CI will now build and release."