# https://taskfile.dev

version: '3'

includes:
  wails:
    taskfile: ./Taskfile.wails.yml
    flatten: true

vars:
  VERSION: ""
  BUILD_DIR: build
  DIST_DIR: build/dist
  PORT: 12580

tasks:
  
  start:
    aliases:
      - http
    cmds:
      - go run ./cli/tingly-box --verbose start --debug --port 12580 --browser=false
  
  https:
    cmds:
      - go run ./cli/tingly-box --verbose start --https --port 12581 --browser=false
  
  record:
    cmds:
      - go run ./cli/tingly-box --verbose start --port 12580 --record-mode=scenario --debug --browser=false
  
  swagger:
    cmds:
      - |
        curl -s http://localhost:{{.PORT}}/swagger.json > swagger.json
  
  codegen:
    cmds:
      - |
        echo install openapi-generator
        echo darwin: brew install openapi-generator
        echo others: npm install @openapitools/openapi-generator-cli -g
        echo ref: https://openapi-generator.tech/docs/installation
      - |
        openapi-generator-cli generate -g typescript-axios -i ./swagger.json -o ./frontend/src/client
  
  cli:build:
    cmds:
      - task: web:dist
      - task: go:build
  
  go:build:
    env:
      ARCH:
      OS:
    cmds:
      - |
        # Get build info
        VERSION="dev"
        GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
        BUILD_TIME="$(date -u '+%Y-%m-%d-%H-%M-%S' 2>/dev/null || echo 'unknown')"
        GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//' 2>/dev/null || echo 'unknown')"
        PLATFORM="${OS}/${ARCH}"

        # Build with ldflags
        mkdir -p build
        LDFLAGS="-X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildTime=${BUILD_TIME} -X main.goVersion=${GO_VERSION} -X main.platform=${PLATFORM}"
        GOOS={{.OS}} GOARCH={{.ARCH}} go build -ldflags="${LDFLAGS}" -o ./build/{{.BIN_NAME}} ./cli/tingly-box
  
  go:test:
    cmds:
      - |
        go test ./internal/...

  tests:interface:
    summary: Run Python interface tests (test_automation)
    cmds:
      - |
       python -m tests.test_automation
  
  cli:dev:
    cmds:
      - task: web:dist
      - task: start
  
  web:dev:
    cmds:
      - |
        echo "This is only for frontend dev, please start your tingly-box server too"
      - |
        cd frontend; pnpm dev
  
  web:build:
    aliases:
      - web:dist
    cmds:
      - task: codegen
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/

  web:build:dev:
    cmds:
      - task: codegen
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build:dev
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/
  
  windows:build:amd64:
    summary: Cross-compiles for Windows AMD64 with CGO enabled (requires mingw-w64)
    cmds:
      - task: windows:build:cross:amd64

  windows:build:arm64:
    summary: Cross-compiles for Windows ARM64 with CGO (requires manual setup, see task output)
    cmds:
      - task: windows:build:cross:arm64

  # CLI build tasks for Windows (uses zig for cross-compilation with CGO)
  windows:cli:build:amd64:
    summary: Cross-compiles CLI for Windows AMD64 (requires zig)
    cmds:
      - task: windows:cli:build:cross:amd64

  windows:cli:build:arm64:
    summary: Cross-compiles CLI for Windows ARM64 (requires zig)
    cmds:
      - task: windows:cli:build:cross:arm64

  windows:cli:build:cross:amd64:
    summary: Cross-compiles CLI for Windows AMD64 with zig
    deps:
      - task: check:zig
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        # Use zig as cross-compiler for Windows AMD64
        CC="zig cc -target x86_64-windows-gnu" \
        CXX="zig c++ -target x86_64-windows-gnu" \
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 \
        go build -buildvcs=false -ldflags="-w -s" -o {{.BIN_DIR}}/{{.BIN_NAME}}-amd64.exe ./cli/tingly-box

  windows:cli:build:cross:arm64:
    summary: Cross-compiles CLI for Windows ARM64 with zig
    deps:
      - task: check:zig
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        # Use zig as cross-compiler for Windows ARM64
        CC="zig cc -target aarch64-windows-gnu" \
        CXX="zig c++ -target aarch64-windows-gnu" \
        GOOS=windows GOARCH=arm64 CGO_ENABLED=1 \
        go build -buildvcs=false -ldflags="-w -s" -o {{.BIN_DIR}}/{{.BIN_NAME}}-arm64.exe ./cli/tingly-box

  check:zig:
    summary: Check if zig is installed
    cmds:
      - |
        if ! command -v zig &> /dev/null; then
          echo "Error: zig not found!"
          echo ""
          echo "To install zig:"
          echo "  macOS:   brew install zig"
          echo "  Or download from: https://ziglang.org/download/"
          echo ""
          exit 1
        fi
        echo "Found: $(zig version)"

  # CLI build tasks for Linux (uses zig for cross-compilation with CGO)
  cli:linux:arm64:
    summary: Cross-compiles CLI for Linux ARM64 (requires zig)
    cmds:
      - task: cli:linux:arm64:cross

  cli:linux:arm64:cross:
    summary: Cross-compiles CLI for Linux ARM64 with zig
    deps:
      - task: check:zig
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        # Use zig as cross-compiler for Linux ARM64
        CC="zig cc -target aarch64-linux-gnu" \
        CXX="zig c++ -target aarch64-linux-gnu" \
        GOOS=linux GOARCH=arm64 CGO_ENABLED=1 \
        go build -buildvcs=false -ldflags="-w -s" -o {{.BIN_DIR}}/{{.BIN_NAME}}-linux-arm64 ./cli/tingly-box

  # Docker build and test tasks for ARM64
  docker:build:arm64:
    summary: Build Docker image for Linux ARM64
    cmds:
      - |
        docker build --platform linux/arm64 -t tingly-box:arm64 -f build/linux/Dockerfile.arm64 .

  docker:test:arm64:
    summary: Run tests in Linux ARM64 Docker container
    deps:
      - task: docker:build:arm64
    cmds:
      - |
        docker run --rm --platform linux/arm64 tingly-box:arm64 \
        sh -c "cd /app && go test ./internal/... -v"

  # remote-cc Service tasks
  remote-cc:build:
    summary: Build the remote-cc-service binary
    cmds:
      - |
        cd cmd/remote-cc
        go mod tidy
        go build -o ../../bin/remote-cc-service .

  remote-cc:run:
    summary: Run remote-cc-service with default configuration
    env:
      RCC_PORT: "18080"
      RCC_SESSION_TIMEOUT: "30m"
    cmds:
      - |
        export RCC_JWT_SECRET="$(python3 - <<'PY'
        import json, os, sys
        path = os.path.expanduser("~/.tingly-box/config.json")
        if not os.path.exists(path):
            print(f"missing config: {path}", file=sys.stderr)
            sys.exit(1)
        with open(path, "r", encoding="utf-8") as f:
            cfg = json.load(f)
        secret = cfg.get("jwt_secret", "")
        if not secret:
            print("jwt_secret missing in config.json", file=sys.stderr)
            sys.exit(1)
        print(secret)
        PY
        )"
        cd cmd/remote-cc && RCC_PORT={{.RCC_PORT | default "18080"}} RCC_SESSION_TIMEOUT={{.RCC_SESSION_TIMEOUT | default "30m"}} go run .

  remote-cc:test:
    summary: Run tests for remote-cc-service
    cmds:
      - |
        go test ./cmd/remote-cc/... -v

  remote-cc:build:cross:
    summary: Cross-compile remote-cc-service for all platforms
    env:
      VERSION: "dev"
    cmds:
      - |
        for os in linux darwin windows; do
          for arch in amd64 arm64; do
            echo "Building for $os/$arch..."
            GOOS=$os GOARCH=$arch \
            go build -ldflags="-X main.version=${VERSION}" \
            -o ./bin/remote-cc-service-$os-$arch \
            ./cmd/remote-cc
          done
        done

  remote-cc-token:build:
    summary: Build the remote-cc-token binary
    cmds:
      - |
        go build -o ./bin/remote-cc-token ./cmd/remote-coder

  remote-cc-token:run:
    summary: Generate an API token (run via SSH)
    cmds:
      - go run ./cmd/remote-coder
