# https://taskfile.dev

version: '3'

includes:
  wails:
    taskfile: ./Taskfile.wails.yml
    flatten: true
  windows-cli:
    taskfile: ./Taskfile.windows.yml
  linux-cli:
    taskfile: ./Taskfile.linux.yml
  docker:
    taskfile: ./Taskfile.docker.yml

vars:
  VERSION: ""
  BUILD_DIR: build
  DIST_DIR: build/dist
  PORT: 12580
  BIN_NAME: "tingly-box"
  BIN_DIR: "bin"

tasks:
  build:
    aliases:
      - cli:build
    cmds:
      - task: web:dist
      - task: go:build
  dev:
    aliases:
      - cli:dev
    cmds:
      - task: web:dist
      - task: start
  
  start:
    aliases:
      - http
    cmds:
      - go run ./cli/tingly-box --verbose start --debug --port 12580 --browser=false
  start:https:
    aliases:
      - https
    cmds:
      - go run ./cli/tingly-box --verbose start --https --port 12581 --browser=false
  record:
    cmds:
      - go run ./cli/tingly-box --verbose start --port 12580 --record-mode=scenario --debug --browser=false
  
  swagger:
    cmds:
      - |
        curl -s http://localhost:{{.PORT}}/swagger.json > swagger.json
  
  codegen:
    cmds:
      - |
        echo install openapi-generator
        echo darwin: brew install openapi-generator
        echo others: npm install @openapitools/openapi-generator-cli -g
        echo ref: https://openapi-generator.tech/docs/installation
      - |
        openapi-generator-cli generate -g typescript-axios -i ./swagger.json -o ./frontend/src/client
  
  go:build:
    env:
      ARCH:
      OS:
    cmds:
      - |
        # Get build info
        VERSION="dev"
        GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
        BUILD_TIME="$(date -u '+%Y-%m-%d-%H-%M-%S' 2>/dev/null || echo 'unknown')"
        GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//' 2>/dev/null || echo 'unknown')"
        PLATFORM="${OS}/${ARCH}"
        
        # Build with ldflags
        mkdir -p build
        LDFLAGS="-X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildTime=${BUILD_TIME} -X main.goVersion=${GO_VERSION} -X main.platform=${PLATFORM}"
        GOOS={{.OS}} GOARCH={{.ARCH}} go build -ldflags="${LDFLAGS}" -o ./build/{{.BIN_NAME}} ./cli/tingly-box
  
  go:test:
    cmds:
      - |
        go test ./internal/...
  
  tests:interface:
    summary: Run Python interface tests (test_automation)
    cmds:
      - |
        python -m tests.test_automation
  
  web:dev:
    cmds:
      - |
        echo "This is only for frontend dev, please start your tingly-box server too"
      - |
        cd frontend; pnpm dev
  
  web:build:
    aliases:
      - web:dist
    cmds:
      - task: codegen
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/
  
  web:build:dev:
    cmds:
      - task: codegen
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build:dev
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/
  
  check:zig:
    summary: Check if zig is installed
    cmds:
      - |
        if ! command -v zig &> /dev/null; then
          echo "Error: zig not found!"
          echo ""
          echo "To install zig:"
          echo "  macOS:   brew install zig"
          echo "  Or download from: https://ziglang.org/download/"
          echo ""
          exit 1
        fi
        echo "Found: $(zig version)"
  
  # remote-coder Service tasks
  remote-coder:run:
    summary: Run remote-coder service via tingly-box rc
    env:
      RCC_PORT: "18080"
      RCC_SESSION_TIMEOUT: "30m"
    cmds:
      - |
        go run ./cli/tingly-box rc
  
  remote-coder:test:
    summary: Run tests for remote-coder service
    cmds:
      - |
        go test ./internal/remote_coder/... -v
  
  remote-coder-token:build:
    summary: Build the remote-coder-token binary
    cmds:
      - |
        go build -o ./bin/remote-coder-token ./cmd/remote-coder
  
  remote-coder-token:run:
    summary: Generate an API token (run via SSH)
    cmds:
      - go run ./cmd/remote-coder

  submodule:
    summary: Show git HEAD and branch for each submodule in libs/
    cmds:
      - |
        for dir in libs/*/; do
          if [ -d "$dir" ]; then
            name=$(basename "$dir")
            cd "$dir"
            head=$(git rev-parse HEAD 2>/dev/null || echo "N/A")
            branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")
            echo "$name:"
            echo "  HEAD: $head"
            echo "  Branch: $branch"
            echo ""
            cd - > /dev/null
          fi
        done
