# https://taskfile.dev

version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  VERSION: ""
  BUILD_DIR: build
  DIST_DIR: build/dist
  
  PACKAGE_PATH: ./internal/wails3
  
  PORT: 12580
  
  APP_NAME: "TinglyBox"
  BIN_NAME: "tingly-box"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  wails:build:
    summary: Builds the application
    cmds:
      - task: codegen
      - task: "{{OS}}:build"
  
  wails:package:
    summary: Packages a production build of the application
    cmds:
      - task: codegen
      - task: "{{OS}}:package"
  
  wails:run:
    summary: Runs the application
    cmds:
      - task: codegen
      - task: "{{OS}}:run"
  
  wails:dev:
    summary: Runs the application in development mode
    cmds:
      - task: codegen
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
  
  wails:binding:
    cmds:
      - wails3 generate bindings -ts -f '-buildvcs=false -gcflags=all="-l"' -clean=true ./internal/wails3 -d frontend/src/bindings
  
  wails:manual:
    cmds:
      - cd frontend; pnpm build:dev:wails
      - |
        mkdir -p internal/gui/dist/
        cp -R frontend/dist/* internal/gui/dist/
      - |
        # Get build info
        VERSION="dev"
        GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
        GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//' 2>/dev/null || echo 'unknown')"
        PLATFORM="$(go env GOOS)/$(go env GOARCH)"

        # Build with ldflags
        LDFLAGS='-X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildTime=${BUILD_TIME} -X main.goVersion=${GO_VERSION} -X main.platform=${PLATFORM} -w -s'
        go build -tags debug -trimpath -buildvcs=false -ldflags="${LDFLAGS}" -o bin/{{.BIN_NAME}} {{.PACKAGE_PATH}}
        mkdir -p bin/{{.APP_NAME}}.app/Contents/{MacOS,Resources}
        cp build/darwin/icons.icns bin/{{.APP_NAME}}.app/Contents/Resources
        cp bin/{{.BIN_NAME}} bin/{{.APP_NAME}}.app/Contents/MacOS
        cp build/darwin/Info.plist bin/{{.APP_NAME}}.app/Contents
        codesign --force --deep --sign - bin/{{.APP_NAME}}.app
  
  codegen:
    cmds:
      - |
        echo install openapi-generator
        echo darwin: brew install openapi-generator
        echo others: npm install @openapitools/openapi-generator-cli -g
        echo ref: https://openapi-generator.tech/docs/installation
      - |
        openapi-generator-cli generate -g typescript-axios -i ./swagger.json -o ./frontend/src/client
  
  swagger:
    cmds:
      - |
        curl -s http://localhost:{{.PORT}}/swagger.json > swagger.json
  
  start:
    cmds:
      - task: go:build
      - ./build/{{.BIN_NAME}} start
  
  cli:build:
    cmds:
      - task: web:dist
      - task: go:build
  
  go:build:
    env:
      ARCH:
      OS:
    cmds:
      - |
        # Get build info
        VERSION="dev"
        GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
        BUILD_TIME="$(date -u '+%Y-%m-%d-%H-%M-%S' 2>/dev/null || echo 'unknown')"
        GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//' 2>/dev/null || echo 'unknown')"
        PLATFORM="${OS}/${ARCH}"

        # Build with ldflags
        mkdir -p build
        LDFLAGS='-X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildTime=${BUILD_TIME} -X main.goVersion=${GO_VERSION} -X main.platform=${PLATFORM}'
        GOOS={{.OS}} GOARCH={{.ARCH}} go build -ldflags="${LDFLAGS}" -o ./build/{{.BIN_NAME}} ./cmd/tingly-box
  
  go:test:
    cmds:
      - |
        go test ./internal/...
  
  cli:dev:
    cmds:
      - task: web:dist
      - |
        go run ./cmd/tingly-box start
  
  web:dev:
    cmds:
      - |
        cd frontend; pnpm dev
  
  web:dist:
    cmds:
      - task: codegen
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/

  web:dist-dev:
    cmds:
      - |
        cd frontend;
        if [ "$CI" = "true" ]; then
          pnpm install --no-frozen-lockfile;
        else
          pnpm install;
        fi;
        pnpm build:dev
      - |
        mkdir -p internal/web/dist/
        cp -R frontend/dist/* internal/web/dist/
  
  gui:build:
    cmds:
      - |
        go build -buildvcs=false -gcflags=all="-l" -o bin/{{.BIN_NAME}} ./wails3
  
  release:
    desc: Create and push git tag with version passed as parameter. run as 'VERSION=v0.0.9 task release'
    cmds:
      - |
        # Get version from parameter
        VERSION="${VERSION:-}"
        
        # Check if version is provided
        if [ -z "$VERSION" ]; then
          echo "Error: VERSION parameter is required!"
          echo "Usage: VERSION=v0.0.9 task release"
          exit 1
        fi
        
        # Validate version format
        if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Invalid version format: $VERSION"
          echo "Expected format: v1.2.3"
          exit 1
        fi
        
        # Check if tag already exists
        if git tag | grep -q "^${VERSION}$"; then
          echo "Error: Tag $VERSION already exists!"
          echo "Choose a new version and try again"
          exit 1
        fi
        
        # Create and push tag
        echo "Creating tag $VERSION..."
        git tag "$VERSION"
        
        echo "Pushing tag to origin..."
        git push origin "$VERSION"
        
        echo "✅ Distribution started! CI will now build and release."