/* tslint:disable */
/* eslint-disable */
/**
 * Tingly Box API
 * A Restful API for managing AI model providers, rules, and load balancing with automatic Swagger documentation generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@tingly-box.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AddProviderRequest {
    /**
     * API base URL
     */
    'api_base': string;
    /**
     * API style
     */
    'api_style': string;
    /**
     * Whether provider is enabled
     */
    'enabled': boolean;
    /**
     * Provider name
     */
    'name': string;
    /**
     * API token
     */
    'token': string;
}
export interface AddProviderResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface DefaultsResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface DeleteProviderResponse {
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface DeleteRuleResponse {
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface FetchProviderModelsResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface GenerateTokenRequest {
    /**
     * Client ID for token generation
     */
    'client_id': string;
}
export interface HistoryResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface ProbeRequest {
    /**
     * Provider name to test against
     */
    'provider': string;
    /**
     * Rule UUID to test
     */
    'rule': string;
}
export interface ProviderModelsResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface ProviderResponse {
    /**
     * Field api_base
     */
    'api_base': string;
    /**
     * Field api_style
     */
    'api_style': string;
    /**
     * Field enabled
     */
    'enabled': boolean;
    /**
     * Field name
     */
    'name': string;
    /**
     * Field token
     */
    'token': string;
}
export interface ProvidersResponse {
    /**
     * Field data
     */
    'data': Array<object>;
    /**
     * Field success
     */
    'success': boolean;
}
export interface RuleResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface RulesResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface ServerActionResponse {
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface SetDefaultsRequest {
    /**
     * Field request_configs
     */
    'request_configs': Array<object>;
}
export interface SetRuleRequest {
    /**
     * Field active
     */
    'active': boolean;
    /**
     * Field current_service_index
     */
    'current_service_index': number;
    /**
     * Field default_model
     */
    'default_model'?: string;
    /**
     * Field provider
     */
    'provider'?: string;
    /**
     * Field request_model
     */
    'request_model': string;
    /**
     * Field response_model
     */
    'response_model': string;
    /**
     * Field services
     */
    'services': Array<object>;
    /**
     * Field tactic
     */
    'tactic': string;
    /**
     * Field tactic_params
     */
    'tactic_params'?: object;
    /**
     * Field uuid
     */
    'uuid': string;
}
export interface SetRuleResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface StatusResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field success
     */
    'success': boolean;
}
export interface ToggleProviderResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}
export interface TokenResponse {
    /**
     * Field token
     */
    'token': string;
    /**
     * Field type
     */
    'type': string;
}
export interface UpdateProviderRequest {
    /**
     * New API base URL
     */
    'api_base'?: string;
    /**
     * New API style
     */
    'api_style'?: string;
    /**
     * New enabled status
     */
    'enabled'?: boolean;
    /**
     * New provider name
     */
    'name'?: string;
    /**
     * New API token
     */
    'token'?: string;
}
export interface UpdateProviderResponse {
    /**
     * Field data
     */
    'data': object;
    /**
     * Field message
     */
    'message': string;
    /**
     * Field success
     */
    'success': boolean;
}

/**
 * DefaultsApi - axios parameter creator
 */
export const DefaultsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get default request configurations
         * @summary Get default request configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DefaultsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/defaults`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set default request configurations
         * @summary Set default request configurations
         * @param {SetDefaultsRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DefaultsPost: async (request: SetDefaultsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1DefaultsPost', 'request', request)
            const localVarPath = `/api/v1/defaults`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultsApi - functional programming interface
 */
export const DefaultsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get default request configurations
         * @summary Get default request configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1DefaultsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DefaultsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1DefaultsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultsApi.apiV1DefaultsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Set default request configurations
         * @summary Set default request configurations
         * @param {SetDefaultsRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1DefaultsPost(request: SetDefaultsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetRuleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1DefaultsPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultsApi.apiV1DefaultsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultsApi - factory interface
 */
export const DefaultsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultsApiFp(configuration)
    return {
        /**
         * Get default request configurations
         * @summary Get default request configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DefaultsGet(options?: RawAxiosRequestConfig): AxiosPromise<DefaultsResponse> {
            return localVarFp.apiV1DefaultsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Set default request configurations
         * @summary Set default request configurations
         * @param {SetDefaultsRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DefaultsPost(request: SetDefaultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SetRuleResponse> {
            return localVarFp.apiV1DefaultsPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultsApi - object-oriented interface
 */
export class DefaultsApi extends BaseAPI {
    /**
     * Get default request configurations
     * @summary Get default request configurations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1DefaultsGet(options?: RawAxiosRequestConfig) {
        return DefaultsApiFp(this.configuration).apiV1DefaultsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set default request configurations
     * @summary Set default request configurations
     * @param {SetDefaultsRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1DefaultsPost(request: SetDefaultsRequest, options?: RawAxiosRequestConfig) {
        return DefaultsApiFp(this.configuration).apiV1DefaultsPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HistoryApi - axios parameter creator
 */
export const HistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get request history
         * @summary Get request history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1HistoryGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoryApi - functional programming interface
 */
export const HistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Get request history
         * @summary Get request history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1HistoryGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1HistoryGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryApi.apiV1HistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HistoryApi - factory interface
 */
export const HistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HistoryApiFp(configuration)
    return {
        /**
         * Get request history
         * @summary Get request history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1HistoryGet(options?: RawAxiosRequestConfig): AxiosPromise<HistoryResponse> {
            return localVarFp.apiV1HistoryGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HistoryApi - object-oriented interface
 */
export class HistoryApi extends BaseAPI {
    /**
     * Get request history
     * @summary Get request history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1HistoryGet(options?: RawAxiosRequestConfig) {
        return HistoryApiFp(this.configuration).apiV1HistoryGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ModelsApi - axios parameter creator
 */
export const ModelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all provider models
         * @summary Get all provider models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProviderModelsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/provider-models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch models for a specific provider
         * @summary Fetch models for a specific provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProviderModelsNamePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/provider-models/:name`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelsApi - functional programming interface
 */
export const ModelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all provider models
         * @summary Get all provider models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProviderModelsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProviderModelsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProviderModelsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.apiV1ProviderModelsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch models for a specific provider
         * @summary Fetch models for a specific provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProviderModelsNamePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FetchProviderModelsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProviderModelsNamePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.apiV1ProviderModelsNamePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModelsApi - factory interface
 */
export const ModelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelsApiFp(configuration)
    return {
        /**
         * Get all provider models
         * @summary Get all provider models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProviderModelsGet(options?: RawAxiosRequestConfig): AxiosPromise<ProviderModelsResponse> {
            return localVarFp.apiV1ProviderModelsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch models for a specific provider
         * @summary Fetch models for a specific provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProviderModelsNamePost(options?: RawAxiosRequestConfig): AxiosPromise<FetchProviderModelsResponse> {
            return localVarFp.apiV1ProviderModelsNamePost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModelsApi - object-oriented interface
 */
export class ModelsApi extends BaseAPI {
    /**
     * Get all provider models
     * @summary Get all provider models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProviderModelsGet(options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).apiV1ProviderModelsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch models for a specific provider
     * @summary Fetch models for a specific provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProviderModelsNamePost(options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).apiV1ProviderModelsNamePost(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProvidersApi - axios parameter creator
 */
export const ProvidersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all configured providers with masked tokens
         * @summary Get all configured providers with masked tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/providers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a provider configuration
         * @summary Delete a provider configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/providers/:name`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get specific provider details with masked token
         * @summary Get specific provider details with masked token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/providers/:name`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update existing provider configuration
         * @summary Update existing provider configuration
         * @param {UpdateProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNamePut: async (request: UpdateProviderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1ProvidersNamePut', 'request', request)
            const localVarPath = `/api/v1/providers/:name`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Toggle provider enabled/disabled status
         * @summary Toggle provider enabled/disabled status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameTogglePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/providers/:name/toggle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Add a new provider configuration
         * @summary Add a new provider configuration
         * @param {AddProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersPost: async (request: AddProviderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1ProvidersPost', 'request', request)
            const localVarPath = `/api/v1/providers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProvidersApi - functional programming interface
 */
export const ProvidersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProvidersApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all configured providers with masked tokens
         * @summary Get all configured providers with masked tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProvidersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a provider configuration
         * @summary Delete a provider configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersNameDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersNameDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersNameDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get specific provider details with masked token
         * @summary Get specific provider details with masked token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersNameGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersNameGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersNameGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update existing provider configuration
         * @summary Update existing provider configuration
         * @param {UpdateProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersNamePut(request: UpdateProviderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersNamePut(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersNamePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Toggle provider enabled/disabled status
         * @summary Toggle provider enabled/disabled status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersNameTogglePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToggleProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersNameTogglePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersNameTogglePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Add a new provider configuration
         * @summary Add a new provider configuration
         * @param {AddProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProvidersPost(request: AddProviderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProvidersPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvidersApi.apiV1ProvidersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProvidersApi - factory interface
 */
export const ProvidersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProvidersApiFp(configuration)
    return {
        /**
         * Get all configured providers with masked tokens
         * @summary Get all configured providers with masked tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersGet(options?: RawAxiosRequestConfig): AxiosPromise<ProvidersResponse> {
            return localVarFp.apiV1ProvidersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a provider configuration
         * @summary Delete a provider configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameDelete(options?: RawAxiosRequestConfig): AxiosPromise<DeleteProviderResponse> {
            return localVarFp.apiV1ProvidersNameDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Get specific provider details with masked token
         * @summary Get specific provider details with masked token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameGet(options?: RawAxiosRequestConfig): AxiosPromise<ProviderResponse> {
            return localVarFp.apiV1ProvidersNameGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Update existing provider configuration
         * @summary Update existing provider configuration
         * @param {UpdateProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNamePut(request: UpdateProviderRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateProviderResponse> {
            return localVarFp.apiV1ProvidersNamePut(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Toggle provider enabled/disabled status
         * @summary Toggle provider enabled/disabled status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersNameTogglePost(options?: RawAxiosRequestConfig): AxiosPromise<ToggleProviderResponse> {
            return localVarFp.apiV1ProvidersNameTogglePost(options).then((request) => request(axios, basePath));
        },
        /**
         * Add a new provider configuration
         * @summary Add a new provider configuration
         * @param {AddProviderRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProvidersPost(request: AddProviderRequest, options?: RawAxiosRequestConfig): AxiosPromise<AddProviderResponse> {
            return localVarFp.apiV1ProvidersPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProvidersApi - object-oriented interface
 */
export class ProvidersApi extends BaseAPI {
    /**
     * Get all configured providers with masked tokens
     * @summary Get all configured providers with masked tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersGet(options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a provider configuration
     * @summary Delete a provider configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersNameDelete(options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersNameDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get specific provider details with masked token
     * @summary Get specific provider details with masked token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersNameGet(options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersNameGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update existing provider configuration
     * @summary Update existing provider configuration
     * @param {UpdateProviderRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersNamePut(request: UpdateProviderRequest, options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersNamePut(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Toggle provider enabled/disabled status
     * @summary Toggle provider enabled/disabled status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersNameTogglePost(options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersNameTogglePost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Add a new provider configuration
     * @summary Add a new provider configuration
     * @param {AddProviderRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProvidersPost(request: AddProviderRequest, options?: RawAxiosRequestConfig) {
        return ProvidersApiFp(this.configuration).apiV1ProvidersPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RulesApi - axios parameter creator
 */
export const RulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete a rule configuration
         * @summary Delete a rule configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/rule/:uuid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get specific rule by UUID
         * @summary Get specific rule by UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/rule/:uuid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create or update a rule configuration
         * @summary Create or update a rule configuration
         * @param {SetRuleRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidPost: async (request: SetRuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1RuleUuidPost', 'request', request)
            const localVarPath = `/api/v1/rule/:uuid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all configured rules
         * @summary Get all configured rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RulesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RulesApi - functional programming interface
 */
export const RulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RulesApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete a rule configuration
         * @summary Delete a rule configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RuleUuidDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteRuleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RuleUuidDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RulesApi.apiV1RuleUuidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get specific rule by UUID
         * @summary Get specific rule by UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RuleUuidGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RuleUuidGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RulesApi.apiV1RuleUuidGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create or update a rule configuration
         * @summary Create or update a rule configuration
         * @param {SetRuleRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RuleUuidPost(request: SetRuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetRuleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RuleUuidPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RulesApi.apiV1RuleUuidPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all configured rules
         * @summary Get all configured rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RulesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RulesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RulesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RulesApi.apiV1RulesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RulesApi - factory interface
 */
export const RulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RulesApiFp(configuration)
    return {
        /**
         * Delete a rule configuration
         * @summary Delete a rule configuration
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidDelete(options?: RawAxiosRequestConfig): AxiosPromise<DeleteRuleResponse> {
            return localVarFp.apiV1RuleUuidDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Get specific rule by UUID
         * @summary Get specific rule by UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidGet(options?: RawAxiosRequestConfig): AxiosPromise<RuleResponse> {
            return localVarFp.apiV1RuleUuidGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Create or update a rule configuration
         * @summary Create or update a rule configuration
         * @param {SetRuleRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RuleUuidPost(request: SetRuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<SetRuleResponse> {
            return localVarFp.apiV1RuleUuidPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all configured rules
         * @summary Get all configured rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RulesGet(options?: RawAxiosRequestConfig): AxiosPromise<RulesResponse> {
            return localVarFp.apiV1RulesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RulesApi - object-oriented interface
 */
export class RulesApi extends BaseAPI {
    /**
     * Delete a rule configuration
     * @summary Delete a rule configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1RuleUuidDelete(options?: RawAxiosRequestConfig) {
        return RulesApiFp(this.configuration).apiV1RuleUuidDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get specific rule by UUID
     * @summary Get specific rule by UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1RuleUuidGet(options?: RawAxiosRequestConfig) {
        return RulesApiFp(this.configuration).apiV1RuleUuidGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create or update a rule configuration
     * @summary Create or update a rule configuration
     * @param {SetRuleRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1RuleUuidPost(request: SetRuleRequest, options?: RawAxiosRequestConfig) {
        return RulesApiFp(this.configuration).apiV1RuleUuidPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all configured rules
     * @summary Get all configured rules
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1RulesGet(options?: RawAxiosRequestConfig) {
        return RulesApiFp(this.configuration).apiV1RulesGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ServerApi - axios parameter creator
 */
export const ServerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Restart the server
         * @summary Restart the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerRestartPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/server/restart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start the server
         * @summary Start the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerStartPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/server/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stop the server gracefully
         * @summary Stop the server gracefully
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerStopPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/server/stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get server status and statistics
         * @summary Get server status and statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServerApi - functional programming interface
 */
export const ServerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServerApiAxiosParamCreator(configuration)
    return {
        /**
         * Restart the server
         * @summary Restart the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ServerRestartPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ServerRestartPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerApi.apiV1ServerRestartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Start the server
         * @summary Start the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ServerStartPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ServerStartPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerApi.apiV1ServerStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stop the server gracefully
         * @summary Stop the server gracefully
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ServerStopPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ServerStopPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerApi.apiV1ServerStopPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get server status and statistics
         * @summary Get server status and statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerApi.apiV1StatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServerApi - factory interface
 */
export const ServerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServerApiFp(configuration)
    return {
        /**
         * Restart the server
         * @summary Restart the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerRestartPost(options?: RawAxiosRequestConfig): AxiosPromise<ServerActionResponse> {
            return localVarFp.apiV1ServerRestartPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Start the server
         * @summary Start the server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerStartPost(options?: RawAxiosRequestConfig): AxiosPromise<ServerActionResponse> {
            return localVarFp.apiV1ServerStartPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Stop the server gracefully
         * @summary Stop the server gracefully
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ServerStopPost(options?: RawAxiosRequestConfig): AxiosPromise<ServerActionResponse> {
            return localVarFp.apiV1ServerStopPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Get server status and statistics
         * @summary Get server status and statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StatusGet(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.apiV1StatusGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServerApi - object-oriented interface
 */
export class ServerApi extends BaseAPI {
    /**
     * Restart the server
     * @summary Restart the server
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ServerRestartPost(options?: RawAxiosRequestConfig) {
        return ServerApiFp(this.configuration).apiV1ServerRestartPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start the server
     * @summary Start the server
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ServerStartPost(options?: RawAxiosRequestConfig) {
        return ServerApiFp(this.configuration).apiV1ServerStartPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stop the server gracefully
     * @summary Stop the server gracefully
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ServerStopPost(options?: RawAxiosRequestConfig) {
        return ServerApiFp(this.configuration).apiV1ServerStopPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get server status and statistics
     * @summary Get server status and statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StatusGet(options?: RawAxiosRequestConfig) {
        return ServerApiFp(this.configuration).apiV1StatusGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TestingApi - axios parameter creator
 */
export const TestingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Test a rule configuration by sending a sample request
         * @summary Test a rule configuration by sending a sample request
         * @param {ProbeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProbePost: async (request: ProbeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1ProbePost', 'request', request)
            const localVarPath = `/api/v1/probe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestingApi - functional programming interface
 */
export const TestingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestingApiAxiosParamCreator(configuration)
    return {
        /**
         * Test a rule configuration by sending a sample request
         * @summary Test a rule configuration by sending a sample request
         * @param {ProbeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProbePost(request: ProbeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProbePost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestingApi.apiV1ProbePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestingApi - factory interface
 */
export const TestingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestingApiFp(configuration)
    return {
        /**
         * Test a rule configuration by sending a sample request
         * @summary Test a rule configuration by sending a sample request
         * @param {ProbeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProbePost(request: ProbeRequest, options?: RawAxiosRequestConfig): AxiosPromise<RuleResponse> {
            return localVarFp.apiV1ProbePost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TestingApi - object-oriented interface
 */
export class TestingApi extends BaseAPI {
    /**
     * Test a rule configuration by sending a sample request
     * @summary Test a rule configuration by sending a sample request
     * @param {ProbeRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1ProbePost(request: ProbeRequest, options?: RawAxiosRequestConfig) {
        return TestingApiFp(this.configuration).apiV1ProbePost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TokenApi - axios parameter creator
 */
export const TokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get existing API token or generate new one
         * @summary Get existing API token or generate new one
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generate a new API token
         * @summary Generate a new API token
         * @param {GenerateTokenRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPost: async (request: GenerateTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('apiV1TokenPost', 'request', request)
            const localVarPath = `/api/v1/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokenApi - functional programming interface
 */
export const TokenApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TokenApiAxiosParamCreator(configuration)
    return {
        /**
         * Get existing API token or generate new one
         * @summary Get existing API token or generate new one
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1TokenGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TokenApi.apiV1TokenGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generate a new API token
         * @summary Generate a new API token
         * @param {GenerateTokenRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenPost(request: GenerateTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1TokenPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TokenApi.apiV1TokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TokenApi - factory interface
 */
export const TokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TokenApiFp(configuration)
    return {
        /**
         * Get existing API token or generate new one
         * @summary Get existing API token or generate new one
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenGet(options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.apiV1TokenGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Generate a new API token
         * @summary Generate a new API token
         * @param {GenerateTokenRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPost(request: GenerateTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.apiV1TokenPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokenApi - object-oriented interface
 */
export class TokenApi extends BaseAPI {
    /**
     * Get existing API token or generate new one
     * @summary Get existing API token or generate new one
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1TokenGet(options?: RawAxiosRequestConfig) {
        return TokenApiFp(this.configuration).apiV1TokenGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generate a new API token
     * @summary Generate a new API token
     * @param {GenerateTokenRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1TokenPost(request: GenerateTokenRequest, options?: RawAxiosRequestConfig) {
        return TokenApiFp(this.configuration).apiV1TokenPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



