# DO NOT EDIT MANUALLY
# This file is generated by: task brew:generate
# To regenerate, run: task brew:generate VERSION=<version>

class TinglyBox < Formula
  desc "Local AI intelligence layer - autonomous AI model proxy and orchestrator"
  homepage "https://github.com/tingly-dev/tingly-box"

  on_macos do
    on_arm do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v1.6.1/tingly-box-darwin-arm64.tar.gz"
      sha256 ""  # Auto-updated on release
    end

    on_intel do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v1.6.1/tingly-box-darwin-amd64.tar.gz"
      sha256 ""  # Auto-updated on release
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v1.6.1/tingly-box-linux-amd64.tar.gz"
      sha256 ""  # Auto-updated on release
    end
  end

  def install
    bin.install "tingly-box"
  end

  test do
    assert_match "v1.6.1", shell_output("#{bin}/tingly-box version 2>&1", 1)
  end
end
